run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - revive

issues:
  exclude-rules:
    - path: resources/.*\.go
      linters: [revive]
      text: "exported"
